### ISSUE TITLE
Jquery Layout

### ISSUE THREAD

**Issue by melloware** [GedMarc/JWebSwing#3]
@GedMarc I really apologize for opening this ticket here but you don't have Issues open on your Jquery Layout fork.  Using your fork we updated for Jquery 3 in PrimeFaces and now some users are reporting this issue when they click a button.

>  /UI Layout Initialization Error
> The center-pane element does not exist.
> The center-pane is a required element.

You can see a Demo of this here by pressing the "Click Me!" button.

https://joinfaces-example.herokuapp.com/customInput.jsf

Their Layout initialized fine, but when they click the button which causes an update to the layout they see that error.  Any guidance?

Much appreciated in advance!

**Comment by GedMarc** [comment]
Hey :)

Good to hear from you again!,
Hmm I can recreate by using $('#j_idt8').layout(); which I think is what is happening.
Quick and easy, $('body').layout();

Call on the parent of the center pane, then it loads no error 👍 also make sure to width-height 100 for full screen effect

**Comment by melloware** [comment]
Hey thanks for getting back to me.

Let me do some more research. Are you saying I should attach to ‘body’ only when they want a full page layout or for ANY layout?  Because it in PF we usually create a div and attach the layout to that.

**Comment by GedMarc** [comment]
Oh nothing as severe as that, Just simply call the parent/wrapping div.

In the example, you had the ui-layout-center div inside the body, so as the body is the parent div, you need to call it on that. What the example is doing is calling .layout() on the center pane itself, so when searching immediate children for "ui-layout-center" no element is found.

The layout will always assume full size of it's owning container. If the container size isn't specified you get what you're seeing there :) It assumes the natural height of the container.

Container (Body/Div) -> Panes ->Header/Footer/Content
```
<body> (or div anywhere on page)
  <div class="ui-layout-north">
      <div class="ui-layout-content">

  <div class="ui-layout-center">
       <div class="ui-layout-header">
       <div class="ui-layout-content">
       <div class="ui-layout-footer">
```

**Comment by melloware** [comment]
OK I am starting to be stumped.  I stepped through the debugger and it is uses 'body' both times and I dumped the configuration object out and they are also identical.  Attached is a zip. If you simply run "mvn clean jetty:run" and got to http://localhost:8080/primefaces-test/test.xhtml its the simplest boiled down issue.

If you point a breakpoint in http://localhost:8080/primefaces-test/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces&v=6.2 in the "_render: function() {" spot you will see its the exact same JQ 'body' and exact same CFG object passed to layout.  It works the first time and fails the second time!

I am stumped!  Example: 
[primefaces-layout.zip](https://github.com/GedMarc/JWebSwing/files/1800670/primefaces-layout.zip)

**Comment by GedMarc** [comment]
Ok so I have to ask before digging a bit deeper :

.ui-layout-unit-content - Is this a custom class you are assigning? I thinking that this is probably a typo? .ui-layout-content?

The custom pane selector should be fine - otherwise it all seems ok, 
Also - is there a particular reason why you are setting the pane selector for the center pane? If it isn't the incorrect class assignment going to have to look deeper xD

![image](https://user-images.githubusercontent.com/5367513/37256784-35ae0860-2568-11e8-8755-574b6631df44.png)

**Comment by melloware** [comment]
1. That style is correct its a custom style assigned to inner panes by PF to allow people to customize the styling.
public final static String UNIT_CONTENT_CLASS = "ui-layout-unit-content ui-widget-content";

2. The paneSelector looks like it has always been doing that and I believe that equates to the generated DIV that gets created?

**Comment by GedMarc** [comment]
Ok so now i'm super confused, 

Take a look at the attachment (just a strip of PF out and running the item manually)
If you open up index.html you can see why I say I don't think the query is calling on the correct parent.

We'll get this one waxed out! It's very hard to debug the innards of PF I'm finding, and the html/js isn't the prettiest output. 
I'm not sure if the layout.js you're using is auto-customized? took a while to find where the ui-layout-unit-content was being set, not sure it was the right place.

[html.zip](https://github.com/GedMarc/JWebSwing/files/1800726/html.zip)

**Comment by melloware** [comment]
itlooks like you are using layout 1.4.4 and just to be apples to apples attached is the exact layout i am using updated for Jquery 3.


[0-jquery.layout.zip](https://github.com/GedMarc/JWebSwing/files/1800734/0-jquery.layout.zip)

**Comment by GedMarc** [comment]
Too many damn folders of the source :) 
Using that zip the example still works tho, so that's a good thing

**Comment by melloware** [comment]
Yeah I stared at it too but in the debugger the .layout() call is definitely on BODY both times with the exact same config.    So I definitely get why it would be a bug if its being called with a different Jquery object but from everything I can tell its being called with the same exact everything the 2nd time as well.  So weird.

**Comment by GedMarc** [comment]
Ok,

Tons and tons of debugging! :)
this = widget var, not the body tag :) 
Somewhere it looks like it is calling on the script tag instead of the parent (definitely calling on the _7 tag)

![image](https://user-images.githubusercontent.com/5367513/37257461-611d811a-2572-11e8-801e-511ce58b6dcd.png)

![image](https://user-images.githubusercontent.com/5367513/37257468-71b9137c-2572-11e8-82b9-0d81508bdb0b.png)

![image](https://user-images.githubusercontent.com/5367513/37257480-b75facf6-2572-11e8-938d-cfd0890aad5c.png)

**Comment by GedMarc** [comment]
wtf xD

**Comment by melloware** [comment]
Form your screenshots how can you tell its on the script tag?  this will be the widgetVar.

So in this line...

`this.layout = this.jq.layout(this.cfg);`

this = widgetVar
this.jq = the Jquery object getting the layout.call.  When I debug this.jq its 'body' every time.

The code in the init function determine what the JQ value is...

```javascript
init: function(cfg) {
        this._super(cfg);

        this.cfg = cfg;
        this.id = this.cfg.id;
        this.jqId = PrimeFaces.escapeClientId(this.id);

        if(this.cfg.full) {                                                 //full
            var dialog = $(this.cfg.center.paneSelector).parents('.ui-dialog-content');
            if(dialog.length == 1) {                                         // full + dialog
                this.jq = dialog;
            } else {
                this.jq = $('body');
            }
        } else if(this.cfg.parent) {                                        //nested
            this.jq = $(PrimeFaces.escapeClientId(this.cfg.parent));
        } else {                                                            //element
            this.jq = $(this.jqId);
        }

        this.renderDeferred();
    },
```

And in the above code since fullpage="true" it makes the JQ = $('body');

**Comment by GedMarc** [comment]
Yeah this is something else, even passing in the exact calls it goes through, 

This one is funny man...

**Comment by melloware** [comment]
1 more debugging hint.  In the pom.xml change the PF version from 6.2 to 6.1 and then run mvn clean jetty:run again you will see the exact same scenario worked with the old Jquery Layout and JQ 2.2.4.   That is why this is so strange to me as well!

**Comment by melloware** [comment]
OK debugging further.  in layou.js in the getPane() method where it tries to get the center pane the first time through this call..

```javascript
, getPane = function (pane) {
                    var sel = options[pane].paneSelector
                    if (sel.substr(0, 1) === "#") { // ID selector
                    // NOTE: elements selected 'by ID' DO NOT have to be 'children'
					    var selector = $N.find(sel);
						var first = selector.eq(0);
                        return $N.find(sel)selector.eq(0);
```
equates to:
```javascript
$('body.ui-layout-container').find('#j_idt5').eq(0);
```
which finds the center unit div id = '#j_idt5'

However when clicking the Click Me button the debugger comes back here and calls the exact same line..

```javascript
$('body.ui-layout-container').find('#j_idt5').eq(0);
```
But this time it returns no object.  If I enter the exact same line in Chrome Console it DOES return the correct DIV.   So its almost like for some reason Jquery is not finding that selector the second time.

**Comment by GedMarc** [comment]
I'm checking to see if the DOM is correctly loaded, or if there is any JQuery update that may impact the search or find method.
Looks like we at the same point, you can run the command at any point I've noticed and it does always return, $N is always body. It may also be related to subsequent calls, 
May have to go from find() to closest() but will need to check the impact on nested layouts

**Comment by GedMarc** [comment]
or even filter() which actually suits the case better without impact on nested

**Comment by melloware** [comment]
I can try that if you want.  Just let me know how you want me to change that line.

**Comment by GedMarc** [comment]
keeping getting hit with jQuery.Deferred exception: cyclic object value getPane@http://localhost:8080/primefaces-test-1.0-SNAPSHOT/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces&v=6.2:1152:50

**Comment by GedMarc** [comment]
OK! - Progress!

Good news, is that the library looks ok, Bad news - it seems you're calling the layout before the dom is built in test.xhtml 
With a lot of alerting points, lengths of 1 are good and solid. I had to fiddle inside the jar file... should be able to just replace the target/../libs/ file with this one to see.

So, in terms of suggestions, 
Simply move the <script id="layout_s" type="text/javascript"> to after the closing tag or just before bodies end? Looks like on the page refresh, because it isn't wrapped in  $(ready) it's firing before the tag has been created.

[primefaces-6.2.zip](https://github.com/GedMarc/JWebSwing/files/1804272/primefaces-6.2.zip)

THAT WAS A NICE ONE!
No library updates required, but I do have 1.6 up and ready

**Comment by GedMarc** [comment]
p.s. i wouldn't use the layout.js in that particular zip anywhere else xD

**Comment by melloware** [comment]
You rock.  Look at my PR that fixes the issue.  https://github.com/primefaces/primefaces/pull/3478

Simply had to move the <script> to encode after the DOM.  I can't believe this wasn't broken before!

I do have 1 more way easier one for you that someone just reported. 

1. Go here: https://www.primefaces.org/showcase-ext/sections/layout/fullPage.jsf

2. Close the West side pane so its closed.

3. Resize the browser.  You will see the West does not remain closed it re-opens.

**Comment by melloware** [comment]
Also let me know when you have your layout 1.6 ready I will update both Primefaces and PrimeFaces Extensions with it.

**Comment by GedMarc** [comment]
So I had to double check..., But interestingly, that exact thing was part of it xD

1.5.12.2 - 1.16.0
------------------
- Updated responsive features to be more dynamic with size control and dynamic construction variations.

 * jquery.layout 1.6.0
 * $Date: 2018-01-27 08:00:00

Turns out I forgot to hit the "release" button xD

**Comment by melloware** [comment]
Awesome will give it a try!   One thing I see is this line...

```        
$P.filter(":visible").find(".ui-layout-container:visible").andSelf().each(function () { 
```

Shouldn't andSelf() be addBack() according to Jquery 3?

**Comment by GedMarc** [comment]
See this is how it is supposed to work, we all work together and good code is supposed to come out, you know?

It all seems to work, no effect on the JQUI tabs at all :) ...dun dun dun, (last dying words?)

**Comment by GedMarc** [comment]
Cool, released as 1.6.1 👍

**Comment by melloware** [comment]
Fantastic. Thanks once again for all your help!

**Comment by melloware** [comment]
I have already imposed enough, but one more weird one if you are bored.  Attached is the example same as before mvn clean jetty:run and go to http://localhost:8080/primefaces-test/test.xhtml

Keep clicking the Load button you will see the size of the layout intermittently change.  Users report this works FINE on all browsers except CHROME.   So someone suggested maybe Chrome is returning some values in decimal instead of long or slightly calculated differently?

[primefaces-layout2.zip](https://github.com/GedMarc/JWebSwing/files/1810758/primefaces-layout2.zip)

**Comment by GedMarc** [comment]
No worries lol, It's all about getting it working great xD

Don't suppose you know which version of chrome? 
Between 56 and 64 there's been a lot of website breaking changes XD I've noticed a lot with streaming sites especially
Are chrome spin offs also suffering? Vivaldi, Opera, etc?

**Comment by melloware** [comment]
So far the only reports have been against Chrome 61 or higher.  I have tested against Chrome 64, Firefox, IE11 and MS Edge and only my Chrome seems to have the issue.

**Comment by GedMarc** [comment]
I got slapped hard by the SAN requirement change they did to certificates this week as well sigh... xD
Will get back to you

**Comment by melloware** [comment]
thanks!  Yeah we got burned by SAN requirement as well at my company!

**Comment by GedMarc** [comment]
Chrome 57 Update 2

**Comment by GedMarc** [comment]
So... Sh8t?

If you enable violation logs, [
Violation] 'load' handler took <N>ms
[Violation] 'load' handler took 163ms
[Violation] 'load' handler took 193ms
[Violation] 'load' handler took 218ms
[Violation] 'load' handler took 228ms
[Violation] 'load' handler took 150ms
[Violation] 'load' handler took 285ms

Only comes up from 57u2 and up, in 58 they turned off the logging again but the issue remains. Anything higher than 50ms is flagged.

Firefox e.g. renders in 32.4 ms
![image](https://user-images.githubusercontent.com/5367513/37417511-2de6b05c-27b9-11e8-9d44-83ddaccfac60.png)

Chrome - 152ms
![image](https://user-images.githubusercontent.com/5367513/37417589-56db97a2-27b9-11e8-8b9e-1408796eb7d2.png)

Is this only with data tables rendering happening? Or is this happening with plain old layouts as well?

Proper fix would be a Performance under the hood thing, technical spike for sure, to me it looks like it's stalling on the data tables render and resize. 
Can't even cloak the component, the sizes are needed to render... xD

**Comment by GedMarc** [comment]
I think a setTimeout('layout',50) may do something, chrome shouldn't need to recalculate the style if the data  tables are rendered first, maybe even a Promise if you don't mind ie10 and up only

**Comment by melloware** [comment]
I don't mind IE10 and up.  Nobody should be using IE9 or lower anyway!

**Comment by melloware** [comment]
Sorry its happening with Any layout.  I can remove the Datatable if you want I believe the issue happens no matter what.  Here is a new test.xhtml without the datatable.

[primefaces-layout.zip](https://github.com/GedMarc/JWebSwing/files/1812419/primefaces-layout.zip)
